### ISSUE TITLE
Testing delivery of the Saga initiator breaks in Rebus 8

### ISSUE THREAD

**Issue by dietermijle** [rebus-org/Rebus.TestHelpers#16]
I have a Saga that is initiated by one message and handles another message.
Put simply, it's somethings like this:

```
public class MySaga : Saga<MySagaData>,
    IAmInitiatedBy<TriggerMySagaMessage>,
    IHandleMessages<UpdateMySagaMessage>
{
    public async Task Handle(TriggerMySagaMessage message)
    {
        if (IsNew) Data.CorrelationId = message.CorrelationId;

        ...
    }

    public async Task Handle(UpdateMySagaMessage message)
    {
        ...
    }
}
```

In my unit tests I have harness that is setup like this:

```
public class MySagaTestHarness
{
    public MySagaTestHarness()
    {
        Saga = new MySaga();
    }

    public MySaga Saga { get; }
}
```

When trying to deliver the `TriggerMySagaMessage` from within my tests, the handle does not seem to get called.

```
[Test]
public void When_TriggeringMySaga_Then_ASagaIsStartedWithCorrectData()
{
    // arrange
    var message = new TriggerMySagaMessage(correlationId);
    var harness = new MySagaTestHarness();

    using (var fixture = SagaFixture.For(() => harness.Saga))
    {
        // act
        fixture.Deliver(message);
        var data = fixture.Data.OfType<MySagaData>().First(); // <-- I get a "Sequence contains no elements" exception here

        // assert
        Assert.That(data, Is.Not.Null);        
    }
}
```

I'm using Rebus 8.4.3 and Rebus.TestHelper 9.1.0.
The same test was working fine in Rebus v6 using Rebus.TestHelpers v7.1.
Any idea what I'm missing here?

**Comment by dietermijle** [comment]
For completeness, I am happy to provide the full code of my test:

```
using System;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;
using Rebus.Handlers;
using Rebus.Sagas;
using Rebus.TestHelpers;

namespace Tests.Sagas;

public class SagaTestFixture
{
    [Test]
    public void When_TriggeringMySaga_Then_ASagaIsStartedWithCorrectData()
    {
        // arrange
        var correlationId = Guid.NewGuid().ToString();
        var message = new TriggerMySagaMessage(correlationId);

        // act
        using var fixture = SagaFixture.For<MySaga>();
        fixture.Deliver(message);
        var data = fixture.Data.OfType<MySagaData>().First();

        // assert
        Assert.That(data, Is.Not.Null);
        Assert.That(data.CorrelationId, Is.EqualTo(correlationId));
    }
}

public class MySaga : Saga<MySagaData>,
    IAmInitiatedBy<TriggerMySagaMessage>,
    IHandleMessages<UpdateMySagaMessage>
{
    public Task Handle(TriggerMySagaMessage message)
    {
        if (IsNew) Data.CorrelationId = message.CorrelationId;
        return Task.CompletedTask;
    }

    public Task Handle(UpdateMySagaMessage message)
    {
        Data.CorrelationId = message.CorrelationId;
        return Task.CompletedTask;
    }

    protected override void CorrelateMessages(ICorrelationConfig<MySagaData> config)
    {
    }
}

public class TriggerMySagaMessage(string correlationId)
{
    public string CorrelationId { get; set; } = correlationId;
}

public class UpdateMySagaMessage(string correlationId)
{
    public string CorrelationId { get; set; } = correlationId;
}

public class MySagaData : ISagaData
{
    public Guid Id { get; set; }
 
    public int Revision { get; set; }

    public string CorrelationId { get; set; }
}
```

**Comment by mookid8000** [comment]
It seems like your `CorrelateMessages` method is missing something. When I made it look like this

```csharp
protected override void CorrelateMessages(ICorrelationConfig<MySagaData> config)
{
    config.Correlate<TriggerMySagaMessage>(m => m.CorrelationId, d => d.CorrelationId);
}
```

your test worked fine.

I am not sure I understand how your test could have been green before though. 🤔  but honestly, I've never really thought about what would happen when `IAmInitiatedBy` was combined with a lack of a corresponding correlation configuration.

Btw. when you've added correlation configuration like

```csharp
config.Correlate<TriggerMySagaMessage>(m => m.CorrelationId, d => d.CorrelationId);
```

and a new saga data instance is created, Rebus will automatically set the `CorrelationId` property of the saga data to the value from the incoming message for you. 🙂

**Comment by dietermijle** [comment]
Thanks @mookid8000, I indeed overlooked the `CorrelateMessages` method in my unit test.
Adding it, does fix the issue.

I wrote this test because I have some other unit tests in my project that fail since I upgraded to the latest version of Rebus.
I tried writing a simple case to reproduce the real issue, but turns out I can not reproduce it that easily.

Do you have any idea what could be the reason for messages not being delivered to the Saga handle in my unit tests?

**Comment by dietermijle** [comment]
@mookid8000 I did some further analysis and found that the issue arises when using the `JsonConstructor` attribute for serializing the message.

When having the following message for example, you'll see that the delivery fails.

```
public class TriggerMySagaMessage
{
    [JsonConstructor]
    public TriggerMySagaMessage(string correlationId, string data)
    {
        CorrelationId = correlationId;
        Data = data;
    }

    public TriggerMySagaMessage(string correlationId)
    {
        CorrelationId = correlationId;
    }
    
    public string CorrelationId { get; }
    
    public string Data { get; }
}
```

**Comment by mookid8000** [comment]
OK I just tried adding `[JsonConstructor]` to my `TriggerMySagaMessage`, and it still works as expected.

Please note though that `JsonConstructorAttribute` exists both in System.Text.Json and Newtonsoft.Json, so it's important that the right one is used (System.Text.Json by default!).

E.g. if I accidentally use `Newtonsoft.Json.JsonConstructorAttribute` I get the following deserialization error:

```
20:24:45 [Warn] [DefaultExceptionLogger] Unhandled exception 1 while handling message with ID "9a01bad0-a4c5-46b7-b190-cb18c24ff372" - System.FormatException: Could not deserialize JSON text: '{"CorrelationId":"d913ea0d-c289-49d8-82ef-b6485ed47d91","Data":null}'
 ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Rebus.TestHelpers.Tests.Bugs.CheckExampleFromBugReport+TriggerMySagaMessage'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
(...)
```

**Comment by dietermijle** [comment]
@mookid8000 We're still using the Newtonsoft serializer. If I see it correctly (https://github.com/rebus-org/Rebus.TestHelpers/blob/fde6c8070399b5f5826a1b71689cad15d7623dfb/Rebus.TestHelpers/SagaFixture.cs#L60C45-L60C69) then this is still the default serializer used in the SagaFixture.
Here's the full code that shows what's wrong.

```
using System;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using NUnit.Framework;
using Rebus.Handlers;
using Rebus.Sagas;
using Rebus.TestHelpers;

namespace Tests.Sagas;

public class SagaTestFixture
{
    [Test]
    public void When_TriggeringMySaga_Then_ASagaIsStartedWithCorrectData()
    {
        // arrange
        var correlationId = Guid.NewGuid().ToString();
        var msgData = Guid.NewGuid().ToString();
        var message = new TriggerMySagaMessage(correlationId, msgData);
        var harness = new MySagaTestHarness();

        // act
        using var fixture = SagaFixture.For(() => harness.MySaga);
        fixture.Deliver(message);

        // assert
        var data = fixture.Data.OfType<MySagaData>().First();
        Assert.That(data, Is.Not.Null);
        Assert.That(data.CorrelationId, Is.EqualTo(correlationId));
        Assert.That(data.Data, Is.EqualTo(msgData));
    }
    
    [Test]
    public void When_UpdatingMySaga_Then_SagaIsUpdatedWithCorrectData()
    {
        // arrange
        var correlationId = Guid.NewGuid().ToString();
        var msgData = Guid.NewGuid().ToString();
        var message = new UpdateMySagaMessage(correlationId, msgData);
        var sagaData = new MySagaData { CorrelationId = correlationId, Data = "empty" };
        var harness = new MySagaTestHarness();

        // act
        using var fixture = SagaFixture.For(() => harness.MySaga);
        fixture.Add(sagaData);
        fixture.Deliver(message);
        var data = fixture.Data.OfType<MySagaData>().First();

        // assert
        Assert.That(data, Is.Not.Null);
        Assert.That(data.CorrelationId, Is.EqualTo(correlationId));
        Assert.That(data.Data, Is.EqualTo(msgData));
    }
}

public class MySagaTestHarness
{
    public MySagaTestHarness()
    {
        MySaga = new MySaga();
    }

    public MySaga MySaga { get; set; }
}

public class MySaga : Saga<MySagaData>,
    IAmInitiatedBy<TriggerMySagaMessage>,
    IHandleMessages<UpdateMySagaMessage>
{
    public Task Handle(TriggerMySagaMessage message)
    {
        if (IsNew) Data.Data = message.Data;
        return Task.CompletedTask;
    }

    public Task Handle(UpdateMySagaMessage message)
    {
        Data.Data = message.Data;
        return Task.CompletedTask;
    }

    protected override void CorrelateMessages(ICorrelationConfig<MySagaData> config)
    {
        config.Correlate<TriggerMySagaMessage>(m => m.CorrelationId, d => d.CorrelationId);
        config.Correlate<UpdateMySagaMessage>(m => m.CorrelationId, d => d.CorrelationId);
    }
}

public class TriggerMySagaMessage
{
    [JsonConstructor]
    public TriggerMySagaMessage(string correlationId, string data)
    {
        CorrelationId = correlationId;
        Data = data;
    }

    public TriggerMySagaMessage(string correlationId)
    {
        CorrelationId = correlationId;
    }
    
    public string CorrelationId { get; }
    
    public string Data { get; }
}

public class UpdateMySagaMessage(string correlationId, string data)
{
    public string CorrelationId { get; } = correlationId;
    
    public string Data { get; } = data;
}

public class MySagaData : ISagaData
{
    public Guid Id { get; set; }
 
    public int Revision { get; set; }

    public string CorrelationId { get; set; }

    public string Data { get; set; }
}
```

The first test fails with below stack trace while the second test runs fine.
```
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Tests.Sagas.SagaTestFixture.When_TriggeringMySaga_Then_ASagaIsStartedWithCorrectData() in C:\Development\Enviso\Services\svc-capacity-center\tests\Enviso.CapacityManagement.Messaging.Tests\Sagas\SagaTestFixture.cs:line 28
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

This exception occurs because the event is not being handled.

**Comment by mookid8000** [comment]
That's the SAGA serializer 🙂 i.e. the serializer used to serialize your saga data.

The message serializer is System.Text.Json and so you'll need to either use `System.Text.Json.JsonConstructorAttribte` or switch to Newtonsoft JSON as the message serializer.

**Comment by dietermijle** [comment]
I'd like to do the 2nd (so switching the message serializer to newtonsoft), but can't seem to find a way to do this in the SagaFixture.

I've tried using the configurer to change the serializer, but it doesn't seem to work:

```
using var fixture = SagaFixture.For<MySaga>(GetBusConfigurer);

...

private static RebusConfigurer GetBusConfigurer() =>
        Configure.With(new BuiltinHandlerActivator()).Serialization(s => s.UseNewtonsoftJson());
```



Can you guide me a bit?

**Comment by mookid8000** [comment]
ah, the problem here is that the message cannot be dispatched to any handlers... and this is because the handler activator is not configured with your saga handler, so the test fixture's Rebus instance will not have any handlers for `TriggerMySagaMessage`.

I've updated the example and split it up into two, so you can [see how it can work with the default serializer](https://github.com/rebus-org/Rebus.TestHelpers/blob/master/Rebus.TestHelpers.Tests/Examples/CheckExampleFromBugReport_SystemTextJson.cs) and [how it can be made to work with Newtonsoft JSON.NET](https://github.com/rebus-org/Rebus.TestHelpers/blob/master/Rebus.TestHelpers.Tests/Examples/CheckExampleFromBugReport_NewtonsoftJsonNet.cs).

**Comment by dietermijle** [comment]
Thanks for the support @mookid8000, got it working now.

Maybe one more question related to the SagaFixture:
When marking the Saga as completed using `MarkAsComplete()` from within the message that is initiating the Saga (`TriggerMySagaMessage` in this example), the `SagaFixture.Data` is not filled. Is this expected?

**Comment by mookid8000** [comment]
Good you got it working 🙂 

Yeah I think that's expected... IIRC there's a `Deleted` event on `SagaFixture` which you can use to detect that a saga has been marked as completed.
